### ISSUE TITLE
Single Project Page

### ISSUE THREAD

**Issue by Kacper-Ksiazek** [Kacper-Ksiazek/portfolio#13]
### Tasks to be done:
- [x] API connection
- [x] General content placement
- [x] Features browser
- [x] Image modals gallery
- [x] Technologies bar
- [x] Recommended projects
### Some backend tasks to catch up
- [x] Link to github for every project and optional live demo link
- [x] Add relevent technologies for every project (those which be used leter on in technologies bar on frontend)
